"use client";

import { useMemo, useState } from "react";
import { completeSale } from "@/app/app/pos/actions";
import { formatCad } from "@/lib/money";

type Product={id:string;name:string;sku:string;barcode:string|null;priceCents:number;quantity:number;vendorName:string};
export function Register({organizationId,storeId,products}:{organizationId:string;storeId:string;products:Product[]}){
  const [search,setSearch]=useState("");const [cart,setCart]=useState<Record<string,number>>({});const [idempotencyKey]=useState(()=>crypto.randomUUID());const visible=products.filter(p=>`${p.name} ${p.sku} ${p.barcode??""}`.toLowerCase().includes(search.toLowerCase()));
  const lines=useMemo(()=>products.filter(p=>cart[p.id]).map(p=>({...p,cartQuantity:cart[p.id]})),[cart,products]);const subtotal=lines.reduce((sum,line)=>sum+line.priceCents*line.cartQuantity,0);
  function add(product:Product){setCart(current=>({...current,[product.id]:Math.min(product.quantity,(current[product.id]??0)+1)}))}
  return <div className="register-grid"><section className="management-card"><h2>Products</h2><input className="search-input" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name, SKU, or barcode"/><div className="product-grid">{visible.map(product=><button type="button" key={product.id} disabled={product.quantity<1} onClick={()=>add(product)}><b>{product.name}</b><span>{product.vendorName}</span><strong>{formatCad(product.priceCents)}</strong><small>{product.quantity} available</small></button>)}</div></section><section className="management-card cart-panel"><h2>Current sale</h2><div className="cart-lines">{lines.map(line=><div key={line.id}><span><b>{line.name}</b><small>{formatCad(line.priceCents)} each</small></span><input type="number" min="1" max={line.quantity} value={line.cartQuantity} onChange={e=>setCart(c=>({...c,[line.id]:Math.max(1,Math.min(line.quantity,Number(e.target.value)))}))}/><button type="button" onClick={()=>setCart(c=>{const next={...c};delete next[line.id];return next})}>Remove</button></div>)}</div>{!lines.length&&<p className="muted">Select a product to begin.</p>}<div className="cart-total"><span>Subtotal</span><b>{formatCad(subtotal)}</b><small>Applicable taxes are calculated and shown in the completed sale.</small></div><form action={completeSale} className="form-stack"><input type="hidden" name="organizationId" value={organizationId}/><input type="hidden" name="storeId" value={storeId}/><input type="hidden" name="idempotencyKey" value={idempotencyKey}/><input type="hidden" name="cart" value={JSON.stringify(lines.map(line=>({productId:line.id,quantity:line.cartQuantity})))}/><label>Payment method<select name="paymentMethod"><option value="cash">Cash</option><option value="card">Card</option><option value="external">External terminal</option></select></label><button className="primary-button" disabled={!lines.length}>Complete sale</button></form></section></div>;
}
