import { and, eq, isNull } from "drizzle-orm";
import Link from "next/link";
import { redirect } from "next/navigation";
import { db } from "@/db";
import { memberships, organizations, rentalAssignments, rentalSpaces, stores, storeTaxComponents, vendors } from "@/db/schema";
import { additionalStorefrontCostCents } from "@/lib/entitlements";
import { requireSession } from "@/lib/current-user";
import { hasPermission, Role } from "@/lib/permissions";
import { createRentalSpace, createStorefront, createVendorAndInvitation, saveTaxComponent } from "./actions";

const provinces=["AB","BC","MB","NB","NL","NS","NT","NU","ON","PE","QC","SK","YT"];
export default async function SetupPage({searchParams}:{searchParams:Promise<{vendorInvitation?:string,error?:string}>}){
  const session=await requireSession();
  const [context]=await db.select({membership:memberships,organization:organizations}).from(memberships).innerJoin(organizations,eq(memberships.organizationId,organizations.id)).where(and(eq(memberships.userId,session.user.id),eq(memberships.status,"active"))).limit(1);
  if(!context)redirect("/app");const role=context.membership.role as Role;const permits=(permission:string)=>hasPermission(role,permission,context.membership.permissions);
  if(!permits("vendors:read"))redirect("/app");
  const storeRows=await db.select().from(stores).where(eq(stores.organizationId,context.organization.id));
  const spaceRows=await db.select({space:rentalSpaces,storeName:stores.name}).from(rentalSpaces).innerJoin(stores,eq(rentalSpaces.storeId,stores.id)).where(eq(stores.organizationId,context.organization.id));
  const taxRows=await db.select({tax:storeTaxComponents,storeName:stores.name}).from(storeTaxComponents).innerJoin(stores,eq(storeTaxComponents.storeId,stores.id)).where(eq(stores.organizationId,context.organization.id));
  const vendorRows=await db.select({vendor:vendors,storeName:stores.name,spaceName:rentalSpaces.name,rentCents:rentalAssignments.monthlyRentCents}).from(vendors).innerJoin(stores,eq(vendors.storeId,stores.id)).leftJoin(rentalAssignments,and(eq(rentalAssignments.vendorId,vendors.id),isNull(rentalAssignments.endsAt))).leftJoin(rentalSpaces,eq(rentalAssignments.spaceId,rentalSpaces.id)).where(eq(vendors.organizationId,context.organization.id));
  const query=await searchParams;const nextStoreCost=additionalStorefrontCostCents(storeRows.length+1)/100;
  return <main className="management-shell"><header><div><p className="eyebrow">RETAIL SETUP</p><h1>Storefronts, spaces, and vendors</h1><p className="muted">Configure each physical location and preserve the rent agreed for every vendor placement.</p></div><Link className="quiet-button" href="/app">Back to overview</Link></header>
    {query.vendorInvitation&&<section className="notice"><b>Vendor created</b><p>Send this secure invitation link to the vendor:</p><code>{query.vendorInvitation}</code></section>}
    {query.error&&<p className="form-error">That record could not be created. Review the values and your plan limits.</p>}
    <section className="metric-grid"><article><span>Storefronts</span><b>{storeRows.length}</b></article><article><span>Active vendors</span><b>{vendorRows.length}</b></article><article><span>Next storefront add-on</span><b>${nextStoreCost} / month</b></article></section>
    {permits("store:manage")&&<section className="management-card"><h2>Add a storefront</h2><p className="muted">The first location is included. Each additional storefront adds $20 CAD per month when billing is connected.</p><form action={createStorefront} className="inline-form"><input type="hidden" name="organizationId" value={context.organization.id}/><label>Name<input name="name" required/></label><label>Province<select name="province" defaultValue="ON">{provinces.map(p=><option key={p}>{p}</option>)}</select></label><label>Timezone<select name="timezone" defaultValue="America/Toronto"><option>America/Toronto</option><option>America/Halifax</option><option>America/Winnipeg</option><option>America/Edmonton</option><option>America/Vancouver</option><option>America/St_Johns</option></select></label><button className="primary-button">Add storefront</button></form></section>}
    {permits("store:manage")&&<section className="management-card"><h2>Store tax configuration</h2><p className="muted">Add the tax components applicable to each storefront. Confirm rates and registration requirements with your accountant.</p><form action={saveTaxComponent} className="inline-form"><input type="hidden" name="organizationId" value={context.organization.id}/><label>Store<select name="storeId">{storeRows.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label><label>Tax<select name="name"><option>HST</option><option>GST</option><option>PST</option><option>QST</option></select></label><label>Rate %<input name="rate" type="number" min="0" max="30" step="0.001" required/></label><label>Registration number<input name="registrationNumber"/></label><button className="primary-button">Save tax</button></form><div className="chip-row">{taxRows.map(({tax,storeName})=><span key={tax.id}><b>{storeName}: {tax.name}</b> {tax.rate}%</span>)}</div></section>}
    {permits("vendors:write")&&<section className="management-card"><h2>Add a rentable space</h2><form action={createRentalSpace} className="inline-form five"><input type="hidden" name="organizationId" value={context.organization.id}/><label>Store<select name="storeId">{storeRows.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label><label>Space name<input name="name" placeholder="Booth A12" required/></label><label>Size<input name="sizeCategory" placeholder="Large"/></label><label>Dimensions<input name="dimensions" placeholder="8 ft x 10 ft"/></label><label>Monthly rent<input name="monthlyRent" type="number" min="0" step="0.01" required/></label><button className="primary-button">Add space</button></form><div className="chip-row">{spaceRows.map(({space,storeName})=><span key={space.id}><b>{space.name}</b> {storeName} · ${(space.monthlyRentCents/100).toFixed(2)}</span>)}</div></section>}
    {permits("vendors:write")&&<section className="management-card"><h2>Add and invite a vendor</h2><form action={createVendorAndInvitation} className="inline-form five"><input type="hidden" name="organizationId" value={context.organization.id}/><label>Store<select name="storeId">{storeRows.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label><label>Vendor ID<input name="code" required/></label><label>Business name<input name="businessName" required/></label><label>Email<input name="email" type="email" required/></label><label>Commission %<input name="commissionRate" type="number" min="0" max="100" step="0.01" required/></label><label>Rental space<select name="spaceId"><option value="">No space assigned</option>{spaceRows.map(({space,storeName})=><option value={space.id} key={space.id}>{storeName}: {space.name} (${(space.monthlyRentCents/100).toFixed(2)})</option>)}</select></label><button className="primary-button">Create vendor</button></form></section>}
    <section className="management-card"><h2>Vendor directory</h2><div className="data-list">{vendorRows.length?vendorRows.map(({vendor,storeName,spaceName,rentCents})=><div key={vendor.id}><span><b>{vendor.code} · {vendor.businessName}</b><small>{vendor.email} · {storeName}</small></span><span><b>{vendor.commissionRate}% commission</b><small>{spaceName?`${spaceName} · $${((rentCents??0)/100).toFixed(2)} monthly rent`:"No rental space"}</small></span></div>):<p className="muted">No vendors yet.</p>}</div></section>
  </main>;
}
