"use server";

import { and, eq, gte, isNull, lt, or } from "drizzle-orm";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { db } from "@/db";
import { auditLog, payouts, refundItems, refunds, rentalAssignments, saleItems, sales, vendors } from "@/db/schema";
import { requireOrganizationPermission } from "@/lib/access";
import { calculatePayoutSnapshot, payoutMonth } from "@/lib/payout-calculations";

const finalizeInput=z.object({organizationId:z.string().uuid(),vendorId:z.string().uuid(),month:z.string().regex(/^\d{4}-\d{2}$/)});
const paidInput=z.object({organizationId:z.string().uuid(),payoutId:z.string().uuid(),paymentMethod:z.enum(["manual","etransfer","cheque","stripe"]),paymentReference:z.string().trim().min(2).max(150),notes:z.string().trim().max(500).optional()});

export async function finalizePayout(formData:FormData){const parsed=finalizeInput.safeParse(Object.fromEntries(formData));if(!parsed.success)redirect("/app/payouts?error=invalid");const {session,membership}=await requireOrganizationPermission(parsed.data.organizationId,"payouts:write");const range=payoutMonth(parsed.data.month);const [vendor]=await db.select().from(vendors).where(and(eq(vendors.id,parsed.data.vendorId),eq(vendors.organizationId,parsed.data.organizationId),eq(vendors.status,"active"))).limit(1);if(!vendor||membership.storeId&&membership.storeId!==vendor.storeId)redirect(`/app/payouts?month=${parsed.data.month}&error=vendor`);const [existing]=await db.select().from(payouts).where(and(eq(payouts.vendorId,vendor.id),eq(payouts.periodStart,range.start),eq(payouts.periodEnd,range.end))).limit(1);if(existing)redirect(`/app/payouts?month=${parsed.data.month}&error=finalized`);
  const sold=await db.select({subtotalCents:saleItems.unitPriceCents,quantity:saleItems.quantity,taxCents:saleItems.taxCents,commissionCents:saleItems.commissionCents}).from(saleItems).innerJoin(sales,eq(saleItems.saleId,sales.id)).where(and(eq(saleItems.vendorId,vendor.id),gte(sales.completedAt,range.start),lt(sales.completedAt,range.end)));const returned=await db.select({subtotalCents:refundItems.subtotalCents,taxCents:refundItems.taxCents,commissionCents:refundItems.commissionCents}).from(refundItems).innerJoin(refunds,eq(refundItems.refundId,refunds.id)).where(and(eq(refundItems.vendorId,vendor.id),gte(refunds.createdAt,range.start),lt(refunds.createdAt,range.end)));const rents=await db.select().from(rentalAssignments).where(and(eq(rentalAssignments.vendorId,vendor.id),lt(rentalAssignments.startsAt,range.end),or(isNull(rentalAssignments.endsAt),gte(rentalAssignments.endsAt,range.start))));const snapshot=calculatePayoutSnapshot(sold.map(item=>({subtotalCents:item.subtotalCents*item.quantity,taxCents:item.taxCents,commissionCents:item.commissionCents})),returned,rents.reduce((sum,item)=>sum+item.monthlyRentCents,0));
  const [payout]=await db.insert(payouts).values({organizationId:vendor.organizationId,storeId:vendor.storeId,vendorId:vendor.id,periodStart:range.start,periodEnd:range.end,...snapshot,finalizedBy:session.user.id}).returning();await db.insert(auditLog).values({organizationId:vendor.organizationId,storeId:vendor.storeId,actorUserId:session.user.id,action:"payout.finalized",entityType:"payout",entityId:payout.id,payload:snapshot});redirect(`/app/payouts?month=${parsed.data.month}&finalized=1`)}

export async function markPayoutPaid(formData:FormData){const parsed=paidInput.safeParse(Object.fromEntries(formData));if(!parsed.success)redirect("/app/payouts?error=payment");const {session,membership}=await requireOrganizationPermission(parsed.data.organizationId,"payouts:write");const [payout]=await db.select().from(payouts).where(and(eq(payouts.id,parsed.data.payoutId),eq(payouts.organizationId,parsed.data.organizationId))).limit(1);if(!payout||payout.status!=="finalized"||membership.storeId&&membership.storeId!==payout.storeId)redirect("/app/payouts?error=payment");await db.transaction(async tx=>{const [updated]=await tx.update(payouts).set({status:"paid",paidAt:new Date(),paymentMethod:parsed.data.paymentMethod,paymentReference:parsed.data.paymentReference,notes:parsed.data.notes||null,updatedAt:new Date()}).where(and(eq(payouts.id,payout.id),eq(payouts.status,"finalized"))).returning();if(!updated)throw new Error("Payout already updated");await tx.insert(auditLog).values({organizationId:payout.organizationId,storeId:payout.storeId,actorUserId:session.user.id,action:"payout.paid",entityType:"payout",entityId:payout.id,payload:{paymentMethod:parsed.data.paymentMethod,paymentReference:parsed.data.paymentReference}})});revalidatePath("/app/payouts");revalidatePath("/vendor/payouts")}
