import { and, eq, sql } from "drizzle-orm";
import Link from "next/link";
import { redirect } from "next/navigation";
import { db } from "@/db";
import { inventoryMovements, memberships, organizations, products, stores, vendors } from "@/db/schema";
import { requireSession } from "@/lib/current-user";
import { formatCad } from "@/lib/money";
import { hasPermission, Role } from "@/lib/permissions";
import { adjustInventory, createProduct, importInventoryCsv } from "./actions";

export default async function InventoryPage({searchParams}:{searchParams:Promise<{error?:string,imported?:string}>}){
  const session=await requireSession();const [context]=await db.select({membership:memberships,organization:organizations}).from(memberships).innerJoin(organizations,eq(memberships.organizationId,organizations.id)).where(and(eq(memberships.userId,session.user.id),eq(memberships.status,"active"))).limit(1);if(!context)redirect("/app");
  const role=context.membership.role as Role;const canAll=hasPermission(role,"inventory:write",context.membership.permissions);const canOwn=hasPermission(role,"own_inventory:write",context.membership.permissions);const canWrite=canAll||canOwn;
  const scope=[eq(products.organizationId,context.organization.id)];if(context.membership.storeId)scope.push(eq(products.storeId,context.membership.storeId));if(role==="vendor"&&context.membership.vendorId)scope.push(eq(products.vendorId,context.membership.vendorId));
  const rows=await db.select({product:products,vendorName:vendors.businessName,storeName:stores.name,quantity:sql<number>`coalesce(sum(${inventoryMovements.quantityDelta}),0)`}).from(products).innerJoin(vendors,eq(products.vendorId,vendors.id)).innerJoin(stores,eq(products.storeId,stores.id)).leftJoin(inventoryMovements,eq(inventoryMovements.productId,products.id)).where(and(...scope)).groupBy(products.id,vendors.businessName,stores.name).orderBy(products.name);
  const storeRows=await db.select().from(stores).where(eq(stores.organizationId,context.organization.id));const vendorRows=await db.select().from(vendors).where(eq(vendors.organizationId,context.organization.id));const query=await searchParams;
  return <main className="management-shell"><header><div><p className="eyebrow">LIVE INVENTORY</p><h1>Products and stock</h1><p className="muted">Every stock change is recorded as an immutable movement.</p></div><Link className="quiet-button" href={role==="vendor"?"/vendor":"/app"}>Back</Link></header>{query.error&&<p className="form-error">The inventory change was rejected. Check the SKU, scope, file template, and available quantity.</p>}{query.imported&&<section className="notice"><b>{query.imported} products imported</b></section>}
  {canAll&&<section className="management-card"><h2>Import products from CSV</h2><p className="muted">Maximum 1,000 rows. Required columns: store, vendor_code, sku, barcode, name, price, tax_code, quantity. The entire file is rejected if any row is invalid.</p><form action={importInventoryCsv} className="inline-form"><input type="hidden" name="organizationId" value={context.organization.id}/><label>CSV file<input name="file" type="file" accept=".csv,text/csv" required/></label><button className="primary-button">Validate and import</button></form></section>}
  {canWrite&&<section className="management-card"><h2>Add a product</h2><form action={createProduct} className="inline-form five"><input type="hidden" name="organizationId" value={context.organization.id}/><label>Store<select name="storeId">{storeRows.filter(s=>!context.membership.storeId||s.id===context.membership.storeId).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>{role!=="vendor"&&<label>Vendor<select name="vendorId">{vendorRows.map(v=><option key={v.id} value={v.id}>{v.code} · {v.businessName}</option>)}</select></label>}{role==="vendor"&&<input type="hidden" name="vendorId" value={context.membership.vendorId??""}/>}<label>SKU<input name="sku" required/></label><label>Barcode<input name="barcode"/></label><label>Name<input name="name" required/></label><label>Price<input name="price" type="number" min="0.01" step="0.01" required/></label><label>Tax<select name="taxCode"><option value="standard">Standard taxes</option><option value="zero">Zero-rated</option><option value="exempt">Exempt</option></select></label><label>Opening quantity<input name="initialQuantity" type="number" min="0" step="1" defaultValue="1" required/></label><button className="primary-button">Add product</button></form></section>}
  <section className="management-card"><h2>Inventory</h2><div className="data-list">{rows.length?rows.map(({product,vendorName,storeName,quantity})=><div key={product.id}><span><b>{product.name}</b><small>{product.sku} · {vendorName} · {storeName} · {formatCad(product.priceCents)}</small></span><span><b>{Number(quantity)} in stock</b>{canWrite&&<form action={adjustInventory} className="adjustment-form"><input type="hidden" name="organizationId" value={context.organization.id}/><input type="hidden" name="productId" value={product.id}/><input name="quantityDelta" type="number" step="1" placeholder="+ / -" required/><select name="reason"><option value="received">Received</option><option value="correction">Correction</option><option value="damaged">Damaged</option><option value="returned">Returned</option><option value="vendor_removed">Vendor removed</option></select><button className="quiet-button">Adjust</button></form>}</span></div>):<p className="muted">No products yet.</p>}</div></section></main>;
}
