import { and, eq, sql } from "drizzle-orm";
import Link from "next/link";
import { redirect } from "next/navigation";
import { db } from "@/db";
import { inventoryMovements, products, stores, vendors } from "@/db/schema";
import { Register } from "@/components/pos/register";
import { requireCurrentOrganizationPermission } from "@/lib/access";

export default async function PosPage({searchParams}:{searchParams:Promise<{store?:string;error?:string;completed?:string}>}){const query=await searchParams;const context=await requireCurrentOrganizationPermission("pos:sell");const storeRows=await db.select().from(stores).where(and(eq(stores.organizationId,context.organization.id),eq(stores.status,"active")));const store=storeRows.find(s=>s.id===(context.membership.storeId??query.store))??storeRows[0];if(!store)redirect("/app/setup");const productRows=await db.select({id:products.id,name:products.name,sku:products.sku,barcode:products.barcode,priceCents:products.priceCents,quantity:sql<number>`coalesce(sum(${inventoryMovements.quantityDelta}),0)`,vendorName:vendors.businessName}).from(products).innerJoin(vendors,eq(products.vendorId,vendors.id)).leftJoin(inventoryMovements,eq(inventoryMovements.productId,products.id)).where(and(eq(products.organizationId,context.organization.id),eq(products.storeId,store.id),eq(products.status,"active"))).groupBy(products.id,vendors.businessName).orderBy(products.name);
return <main className="management-shell wide"><header><div><p className="eyebrow">BUILT-IN POS</p><h1>{store.name}</h1><p className="muted">Stock and commissions are committed atomically when a sale completes.</p></div><div className="header-actions">{!context.membership.storeId&&storeRows.map(s=><Link className="quiet-button" key={s.id} href={`/app/pos?store=${s.id}`}>{s.name}</Link>)}<Link className="quiet-button" href="/app">Exit POS</Link></div></header>{query.error&&<p className="form-error">Checkout was rejected. Confirm stock availability and storefront tax configuration.</p>}{query.completed&&<section className="notice"><b>Sale completed</b><p>Order {query.completed} was recorded successfully.</p></section>}<Register organizationId={context.organization.id} storeId={store.id} products={productRows.map(p=>({...p,quantity:Number(p.quantity)}))}/></main>}
